target_sources(lrdp_protocol PRIVATE src/reconnect_wire.cpp)
if(BUILD_TESTING)
  add_executable(lrdp_reconnect_wire_tests tests/reconnect_wire_tests.cpp)
  target_link_libraries(lrdp_reconnect_wire_tests PRIVATE lrdp_protocol)
  add_test(NAME reconnect_wire COMMAND lrdp_reconnect_wire_tests)
endif()
if(LRDP_BUILD_SERVER)
  add_library(lrdp_session_registry src/session_registry.cpp)
  target_link_libraries(lrdp_session_registry PUBLIC lrdp_protocol OpenSSL::Crypto)
  target_compile_options(lrdp_session_registry PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
  if(BUILD_TESTING)
    add_executable(lrdp_session_registry_tests tests/session_registry_tests.cpp)
    target_link_libraries(lrdp_session_registry_tests PRIVATE lrdp_session_registry)
    add_test(NAME session_registry COMMAND lrdp_session_registry_tests)
  endif()
endif()
