target_sources(lrdp_protocol PRIVATE src/drive_wire.cpp src/drive_protocol.cpp src/drive_bridge.cpp)
if(BUILD_TESTING)
  foreach(name IN ITEMS protocol bridge)
    add_executable(lrdp_drive_${name}_tests tests/drive_${name}_tests.cpp)
    target_link_libraries(lrdp_drive_${name}_tests PRIVATE lrdp_protocol)
    add_test(NAME drive_${name} COMMAND lrdp_drive_${name}_tests)
  endforeach()
endif()
