target_sources(lrdp_protocol PRIVATE src/avc444.cpp)
if(BUILD_TESTING)
  add_executable(lrdp_avc444_tests tests/avc444_tests.cpp)
  target_link_libraries(lrdp_avc444_tests PRIVATE lrdp_protocol)
  add_test(NAME avc444 COMMAND lrdp_avc444_tests)
endif()
if(BUILD_TESTING)
  add_executable(lrdp_avc444_wire_tests tests/avc444_wire_tests.cpp)
  target_link_libraries(lrdp_avc444_wire_tests PRIVATE lrdp_protocol)
  add_test(NAME avc444_wire COMMAND lrdp_avc444_wire_tests)
  if(TARGET lrdp_video)
    add_executable(lrdp_avc444_codec_tests tests/avc444_codec_tests.cpp)
    target_link_libraries(lrdp_avc444_codec_tests PRIVATE lrdp_video)
    add_test(NAME avc444_codec COMMAND lrdp_avc444_codec_tests)
  endif()
endif()
