target_sources(lrdp_protocol PRIVATE src/clipboard_html.cpp src/clipboard_dib.cpp)
if(TARGET lrdp_x11)
  find_package(PNG QUIET)
  if(PNG_FOUND)
    target_sources(lrdp_x11 PRIVATE src/clipboard_png.cpp)
    target_link_libraries(lrdp_x11 PUBLIC PNG::PNG)
    target_compile_definitions(lrdp_x11 PRIVATE LRDP_HAVE_PNG=1)
  endif()
endif()
if(BUILD_TESTING)
  add_executable(lrdp_rich_clipboard_tests tests/rich_clipboard_tests.cpp)
  target_link_libraries(lrdp_rich_clipboard_tests PRIVATE lrdp_protocol)
  add_test(NAME rich_clipboard COMMAND lrdp_rich_clipboard_tests)
endif()
if(BUILD_TESTING AND TARGET lrdp_x11 AND XVFB_EXECUTABLE)
  add_executable(lrdp_rich_x11_tests tests/rich_x11_tests.cpp)
  target_link_libraries(lrdp_rich_x11_tests PRIVATE lrdp_x11)
  if(PNG_FOUND)
    target_compile_definitions(lrdp_rich_x11_tests PRIVATE LRDP_TEST_PNG=1)
  endif()
  add_test(NAME rich_x11_clipboard COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/xvfb.py $<TARGET_FILE:lrdp_rich_x11_tests>)
  set_tests_properties(rich_x11_clipboard PROPERTIES TIMEOUT 40)
endif()
if(BUILD_TESTING AND TARGET lrdp_headless_tests)
  add_executable(lrdp_rich_native_app tests/rich_native_app.cpp)
  target_include_directories(lrdp_rich_native_app PRIVATE ${X11_INCLUDE_DIR})
  target_link_libraries(lrdp_rich_native_app PRIVATE ${X11_LIBRARIES})
  add_test(NAME rich_clipboard_session COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/rich_integration.py $<TARGET_FILE:lrdpd> $<TARGET_FILE:lrdp_rich_native_app>)
  set_tests_properties(rich_clipboard_session PROPERTIES TIMEOUT 45)
endif()
