option(LRDP_GSSAPI "Enable system GSSAPI CredSSP/NLA authentication" ON)
option(LRDP_TEST_NTLM "Require independent GSS-NTLMSSP/FreeRDP NLA tests" OFF)
if(LRDP_GSSAPI)
  find_path(GSSAPI_INCLUDE_DIR gssapi/gssapi.h)
  find_library(GSSAPI_LIBRARY NAMES gssapi_krb5 gssapi)
  if(GSSAPI_INCLUDE_DIR AND GSSAPI_LIBRARY)
    add_library(lrdp_security src/credssp.cpp src/gss_provider.cpp src/nla_transport.cpp)
    target_include_directories(lrdp_security PRIVATE ${GSSAPI_INCLUDE_DIR})
    target_link_libraries(lrdp_security PUBLIC lrdp_protocol OpenSSL::SSL OpenSSL::Crypto ${GSSAPI_LIBRARY})
    target_compile_options(lrdp_security PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
    target_link_libraries(lrdpd PRIVATE lrdp_security)
    target_compile_definitions(lrdpd PRIVATE LRDP_HAVE_GSSAPI=1)
    if(BUILD_TESTING)
      add_executable(lrdp_credssp_tests tests/credssp_tests.cpp)
      target_link_libraries(lrdp_credssp_tests PRIVATE lrdp_security)
      add_test(NAME credssp COMMAND lrdp_credssp_tests)
      if(LRDP_TEST_NTLM)
        if(NOT FREERDP_CLIENT OR NOT XVFB_EXECUTABLE)
          message(FATAL_ERROR "LRDP_TEST_NTLM requires FreeRDP, Xvfb and system GSS-NTLMSSP")
        endif()
        add_test(NAME client_nla COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/xvfb.py
          ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/nla_interop.py $<TARGET_FILE:lrdpd> ${FREERDP_CLIENT})
        set_tests_properties(client_nla PROPERTIES TIMEOUT 90)
      endif()
    endif()
  elseif(LRDP_TEST_NTLM)
    message(FATAL_ERROR "LRDP_TEST_NTLM requires system GSSAPI development files")
  endif()
endif()
if(PkgConfig_FOUND)
  pkg_check_modules(PIPEWIRE QUIET IMPORTED_TARGET libpipewire-0.3)
endif()
option(LRDP_AUDIO "Enable per-session PipeWire virtual audio devices" ON)
if(LRDP_AUDIO AND PIPEWIRE_FOUND)
  add_library(lrdp_audio_devices src/pipewire_audio.cpp)
  target_link_libraries(lrdp_audio_devices PUBLIC lrdp_protocol PkgConfig::PIPEWIRE)
  target_compile_options(lrdp_audio_devices PRIVATE -Wall -Wextra -Wconversion -Wshadow)
  target_link_libraries(lrdpd PRIVATE lrdp_audio_devices)
  target_compile_definitions(lrdpd PRIVATE LRDP_HAVE_AUDIO=1)
  if(BUILD_TESTING)
    find_program(PIPEWIRE_EXECUTABLE pipewire)
    find_program(PW_LINK_EXECUTABLE pw-link)
    if(PIPEWIRE_EXECUTABLE AND PW_LINK_EXECUTABLE)
      add_executable(lrdp_audio_device_fixture tests/audio_device_fixture.cpp)
      target_link_libraries(lrdp_audio_device_fixture PRIVATE lrdp_audio_devices)
      add_test(NAME pipewire_audio COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/pipewire_test.py $<TARGET_FILE:lrdp_audio_device_fixture>)
      set_tests_properties(pipewire_audio PROPERTIES TIMEOUT 60)
    endif()
  endif()
endif()
option(LRDP_PORTAL "Enable consent-based Wayland desktop capture and input" ON)
if(LRDP_PORTAL AND PkgConfig_FOUND)
  pkg_check_modules(GIO QUIET IMPORTED_TARGET gio-2.0 gio-unix-2.0)
  if(GIO_FOUND)
    add_library(lrdp_portal_session src/portal_session.cpp)
    target_link_libraries(lrdp_portal_session PUBLIC lrdp_protocol PkgConfig::GIO)
    target_compile_options(lrdp_portal_session PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
    if(BUILD_TESTING)
      add_executable(lrdp_portal_tests tests/portal_tests.cpp)
      target_link_libraries(lrdp_portal_tests PRIVATE lrdp_portal_session)
      add_test(NAME portal_session COMMAND lrdp_portal_tests)
      set_tests_properties(portal_session PROPERTIES TIMEOUT 30)
    endif()
    if(PIPEWIRE_FOUND)
      add_library(lrdp_portal src/pipewire_capture.cpp src/portal_desktop.cpp)
      target_link_libraries(lrdp_portal PUBLIC lrdp_portal_session lrdp_capture PkgConfig::PIPEWIRE)
      target_compile_options(lrdp_portal PRIVATE -Wall -Wextra -Wconversion -Wshadow)
      target_link_libraries(lrdpd PRIVATE lrdp_portal)
      target_compile_definitions(lrdpd PRIVATE LRDP_HAVE_PORTAL=1)
    endif()
  endif()
endif()
