target_sources(lrdp_protocol PRIVATE src/network_autodetect.cpp src/session_network.cpp)
if(BUILD_TESTING)
  add_executable(lrdp_network_tests tests/network_tests.cpp)
  target_link_libraries(lrdp_network_tests PRIVATE lrdp_protocol)
  add_test(NAME network_autodetect COMMAND lrdp_network_tests)
  add_executable(lrdp_network_session_tests tests/network_session_tests.cpp)
  target_link_libraries(lrdp_network_session_tests PRIVATE lrdp_protocol)
  add_test(NAME network_session_state COMMAND lrdp_network_session_tests)
endif()
if(BUILD_TESTING AND LRDP_BUILD_SERVER)
  add_test(NAME network_session COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/network_integration.py $<TARGET_FILE:lrdpd>)
  set_tests_properties(network_session PROPERTIES TIMEOUT 60)
endif()
if(BUILD_TESTING AND LRDP_BUILD_SERVER AND FREERDP_CLIENT AND XVFB_EXECUTABLE)
  add_test(NAME network_client COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/xvfb.py
    ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/network_client_interop.py $<TARGET_FILE:lrdpd> ${FREERDP_CLIENT})
  set_tests_properties(network_client PROPERTIES TIMEOUT 45)
endif()
