add_library(lrdp_mime src/mime_clipboard.cpp)
target_link_libraries(lrdp_mime PUBLIC lrdp_protocol)
target_compile_options(lrdp_mime PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
if(TARGET lrdp_portal_session)
  target_link_libraries(lrdp_portal_session PUBLIC lrdp_mime)
endif()
if(BUILD_TESTING)
  add_executable(lrdp_mime_clipboard_tests tests/mime_clipboard_tests.cpp)
  target_link_libraries(lrdp_mime_clipboard_tests PRIVATE lrdp_mime)
  add_test(NAME mime_clipboard COMMAND lrdp_mime_clipboard_tests)
endif()
