target_sources(lrdp_protocol PRIVATE src/drive_wire.cpp src/drive_protocol.cpp src/drive_bridge.cpp src/drive_filesystem.cpp src/session_drives.cpp)
if(BUILD_TESTING)
  add_executable(lrdp_drive_protocol_tests tests/drive_protocol_tests.cpp)
  target_link_libraries(lrdp_drive_protocol_tests PRIVATE lrdp_protocol)
  add_test(NAME drive_protocol COMMAND lrdp_drive_protocol_tests)
endif()
if(BUILD_TESTING)
  add_executable(lrdp_drive_bridge_tests tests/drive_bridge_tests.cpp)
  target_link_libraries(lrdp_drive_bridge_tests PRIVATE lrdp_protocol)
  add_test(NAME drive_bridge COMMAND lrdp_drive_bridge_tests)
endif()
if(BUILD_TESTING AND LRDP_BUILD_SERVER)
  add_executable(lrdp_drive_session_fixture tests/drive_session_fixture.cpp src/transport.cpp)
  target_link_libraries(lrdp_drive_session_fixture PRIVATE lrdp_protocol OpenSSL::SSL OpenSSL::Crypto)
  add_test(NAME drive_session COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/drive_session.py $<TARGET_FILE:lrdp_drive_session_fixture>)
  set_tests_properties(drive_session PROPERTIES TIMEOUT 90)
endif()

option(LRDP_FUSE "Enable private libfuse3 redirected drive mounts" ON)
if(LRDP_BUILD_SERVER AND LRDP_FUSE AND PkgConfig_FOUND)
  pkg_check_modules(FUSE3 QUIET IMPORTED_TARGET fuse3>=3.10)
  if(FUSE3_FOUND)
    add_library(lrdp_drive_mount src/drive_mount.cpp)
    target_link_libraries(lrdp_drive_mount PUBLIC lrdp_protocol PkgConfig::FUSE3 OpenSSL::Crypto)
    target_compile_options(lrdp_drive_mount PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
    target_link_libraries(lrdpd PRIVATE lrdp_drive_mount)
    target_compile_definitions(lrdpd PRIVATE LRDP_HAVE_FUSE=1)
  endif()
endif()
