option(LRDP_PRINTING "Build owner-only native raw printer submission" ON)
if(LRDP_BUILD_SERVER AND LRDP_PRINTING)
  add_library(lrdp_native_print src/print_native_wire.cpp src/print_source.cpp src/print_endpoint.cpp src/print_client.cpp)
  target_link_libraries(lrdp_native_print PUBLIC lrdp_protocol OpenSSL::Crypto)
  target_compile_options(lrdp_native_print PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
  add_executable(lrdp-print src/print_main.cpp)
  target_link_libraries(lrdp-print PRIVATE lrdp_native_print)
  target_compile_options(lrdp-print PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
  target_link_libraries(lrdpd PRIVATE lrdp_native_print)
  target_compile_definitions(lrdpd PRIVATE LRDP_HAVE_PRINTING=1)
  install(TARGETS lrdp-print RUNTIME DESTINATION bin)
endif()

if(LRDP_BUILD_SERVER AND LRDP_PRINTING AND BUILD_TESTING)
  add_executable(lrdp_printer_native_tests tests/printer_native_tests.cpp)
  target_link_libraries(lrdp_printer_native_tests PRIVATE lrdp_native_print)
  add_test(NAME printer_native COMMAND lrdp_printer_native_tests)
  add_test(NAME printer_session COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/printer_integration.py $<TARGET_FILE:lrdpd> $<TARGET_FILE:lrdp-print>)
  set_tests_properties(printer_native printer_session PROPERTIES TIMEOUT 45)
endif()
