option(LRDP_HEADLESS "Enable private, resizable Xorg dummy desktop sessions" ON)
if(LRDP_HEADLESS AND TARGET lrdp_x11)
  add_library(lrdp_headless src/child_process.cpp src/headless_server.cpp src/randr_outputs.cpp src/headless_desktop.cpp)
  target_link_libraries(lrdp_headless PUBLIC lrdp_x11 OpenSSL::Crypto)
  target_compile_options(lrdp_headless PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
  target_link_libraries(lrdpd PRIVATE lrdp_headless)
  target_compile_definitions(lrdpd PRIVATE LRDP_HAVE_HEADLESS=1)
  if(BUILD_TESTING)
    find_program(XORG_EXECUTABLE NAMES Xorg PATHS /usr/lib/xorg NO_DEFAULT_PATH)
    if(XORG_EXECUTABLE)
      add_executable(lrdp_headless_tests tests/headless_tests.cpp)
      target_link_libraries(lrdp_headless_tests PRIVATE lrdp_headless)
      add_test(NAME headless_desktop COMMAND lrdp_headless_tests)
      set_tests_properties(headless_desktop PROPERTIES TIMEOUT 60)
      add_executable(lrdp_clipboard_native_app tests/clipboard_native_app.cpp)
      target_include_directories(lrdp_clipboard_native_app PRIVATE ${X11_INCLUDE_DIR})
      target_link_libraries(lrdp_clipboard_native_app PRIVATE ${X11_LIBRARIES})
      add_test(NAME clipboard_file_session COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/clipboard_files_integration.py
        $<TARGET_FILE:lrdpd> $<TARGET_FILE:lrdp_clipboard_native_app>)
      set_tests_properties(clipboard_file_session PROPERTIES TIMEOUT 60)
      add_executable(lrdp_headless_app tests/headless_app.cpp)
      target_include_directories(lrdp_headless_app PRIVATE ${X11_INCLUDE_DIR})
      target_link_libraries(lrdp_headless_app PRIVATE ${X11_LIBRARIES})
      add_test(NAME headless_session COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/headless_integration.py
        $<TARGET_FILE:lrdpd> $<TARGET_FILE:lrdp_headless_app>)
      set_tests_properties(headless_session PROPERTIES TIMEOUT 60)
      add_test(NAME headless_initial_monitors COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/headless_integration.py
        $<TARGET_FILE:lrdpd> $<TARGET_FILE:lrdp_headless_app> --initial-monitors)
      set_tests_properties(headless_initial_monitors PROPERTIES TIMEOUT 60)
    endif()
  endif()
endif()
