# Optional native integrations are linked only when their documented dependencies exist.
option(LRDP_GSSAPI "Enable system GSSAPI CredSSP/NLA authentication" ON)
if(LRDP_GSSAPI)
  find_path(GSSAPI_INCLUDE_DIR gssapi/gssapi.h)
  find_library(GSSAPI_LIBRARY NAMES gssapi_krb5 gssapi)
  if(GSSAPI_INCLUDE_DIR AND GSSAPI_LIBRARY)
    add_library(lrdp_security src/credssp.cpp src/gss_provider.cpp src/nla_transport.cpp)
    target_include_directories(lrdp_security PRIVATE ${GSSAPI_INCLUDE_DIR})
    target_link_libraries(lrdp_security PUBLIC lrdp_protocol OpenSSL::SSL OpenSSL::Crypto ${GSSAPI_LIBRARY})
    target_compile_options(lrdp_security PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
    target_link_libraries(lrdpd PRIVATE lrdp_security)
    target_compile_definitions(lrdpd PRIVATE LRDP_HAVE_GSSAPI=1)
    if(BUILD_TESTING)
      add_executable(lrdp_credssp_tests tests/credssp_tests.cpp)
      target_link_libraries(lrdp_credssp_tests PRIVATE lrdp_security)
      add_test(NAME credssp COMMAND lrdp_credssp_tests)
      find_library(GSS_NTLMSSP_LIBRARY NAMES gssntlmssp PATH_SUFFIXES gssntlmssp)
      if(FREERDP_CLIENT AND XVFB_EXECUTABLE AND GSS_NTLMSSP_LIBRARY)
        add_test(NAME client_nla COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/xvfb.py
          ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/nla_interop.py $<TARGET_FILE:lrdpd> ${FREERDP_CLIENT})
        set_tests_properties(client_nla PROPERTIES TIMEOUT 90)
      endif()
    endif()
  else()
    message(STATUS "GSSAPI unavailable: NLA authentication disabled")
  endif()
endif()
