target_sources(lrdp_protocol PRIVATE src/reconnect_wire.cpp)
if(BUILD_TESTING)
  add_executable(lrdp_reconnect_wire_tests tests/reconnect_wire_tests.cpp)
  target_link_libraries(lrdp_reconnect_wire_tests PRIVATE lrdp_protocol)
  add_test(NAME reconnect_wire COMMAND lrdp_reconnect_wire_tests)
endif()
if(LRDP_BUILD_SERVER)
  add_library(lrdp_session_registry src/session_registry.cpp)
  target_link_libraries(lrdp_session_registry PUBLIC lrdp_protocol OpenSSL::Crypto)
  target_compile_options(lrdp_session_registry PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
  if(BUILD_TESTING)
    add_executable(lrdp_session_registry_tests tests/session_registry_tests.cpp)
    target_link_libraries(lrdp_session_registry_tests PRIVATE lrdp_session_registry)
    add_test(NAME session_registry COMMAND lrdp_session_registry_tests)
  endif()
endif()
if(TARGET lrdp_headless)
  add_library(lrdp_persistent src/session_broker.cpp src/persistent_desktop.cpp)
  target_link_libraries(lrdp_persistent PUBLIC lrdp_headless lrdp_session_registry)
  target_compile_options(lrdp_persistent PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
  target_link_libraries(lrdpd PRIVATE lrdp_persistent)
  add_executable(lrdp-sessiond src/sessiond_main.cpp)
  add_executable(lrdp-sessionctl src/sessionctl_main.cpp)
  target_link_libraries(lrdp-sessiond PRIVATE lrdp_persistent)
  target_link_libraries(lrdp-sessionctl PRIVATE lrdp_persistent)
  install(TARGETS lrdp-sessiond lrdp-sessionctl RUNTIME DESTINATION bin)
endif()
if(BUILD_TESTING AND TARGET lrdp_headless_app AND TARGET lrdp-sessiond)
  add_test(NAME persistent_reconnect COMMAND ${Python3_EXECUTABLE}
    ${CMAKE_CURRENT_SOURCE_DIR}/tests/reconnect_integration.py $<TARGET_FILE:lrdpd>
    $<TARGET_FILE:lrdp-sessiond> $<TARGET_FILE:lrdp-sessionctl> $<TARGET_FILE:lrdp_headless_app>)
  set_tests_properties(persistent_reconnect PROPERTIES TIMEOUT 90)
endif()

if(BUILD_TESTING AND LRDP_TEST_NTLM AND TARGET lrdp_security AND TARGET lrdp-sessiond)
  add_test(NAME persistent_nla COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/xvfb.py
    ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/persistent_nla.py
    $<TARGET_FILE:lrdpd> ${FREERDP_CLIENT} $<TARGET_FILE:lrdp-sessiond> $<TARGET_FILE:lrdp_headless_app>)
  set_tests_properties(persistent_nla PROPERTIES TIMEOUT 90)
endif()
