# Optional native integrations are linked only when their documented dependencies exist.
option(LRDP_GSSAPI "Enable system GSSAPI CredSSP/NLA authentication" ON)
option(LRDP_TEST_NTLM "Require independent GSS-NTLMSSP/FreeRDP NLA tests" OFF)
if(LRDP_GSSAPI)
  find_path(GSSAPI_INCLUDE_DIR gssapi/gssapi.h)
  find_library(GSSAPI_LIBRARY NAMES gssapi_krb5 gssapi)
  if(GSSAPI_INCLUDE_DIR AND GSSAPI_LIBRARY)
    add_library(lrdp_security src/credssp.cpp src/gss_provider.cpp src/nla_transport.cpp)
    target_include_directories(lrdp_security PRIVATE ${GSSAPI_INCLUDE_DIR})
    target_link_libraries(lrdp_security PUBLIC lrdp_protocol OpenSSL::SSL OpenSSL::Crypto ${GSSAPI_LIBRARY})
    target_compile_options(lrdp_security PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
    target_link_libraries(lrdpd PRIVATE lrdp_security)
    target_compile_definitions(lrdpd PRIVATE LRDP_HAVE_GSSAPI=1)
    if(BUILD_TESTING)
      add_executable(lrdp_credssp_tests tests/credssp_tests.cpp)
      target_link_libraries(lrdp_credssp_tests PRIVATE lrdp_security)
      add_test(NAME credssp COMMAND lrdp_credssp_tests)
      if(LRDP_TEST_NTLM)
        if(NOT FREERDP_CLIENT OR NOT XVFB_EXECUTABLE)
          message(FATAL_ERROR "LRDP_TEST_NTLM requires FreeRDP, Xvfb and the system GSS-NTLMSSP package")
        endif()
        add_test(NAME client_nla COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/xvfb.py
          ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/nla_interop.py $<TARGET_FILE:lrdpd> ${FREERDP_CLIENT})
        set_tests_properties(client_nla PROPERTIES TIMEOUT 90)
      endif()
    endif()
  elseif(LRDP_TEST_NTLM)
    message(FATAL_ERROR "LRDP_TEST_NTLM requires system GSSAPI development files")
  else()
    message(STATUS "GSSAPI unavailable: NLA authentication disabled")
  endif()
endif()
option(LRDP_PORTAL "Enable consent-based desktop portal integration" ON)
if(LRDP_PORTAL AND PkgConfig_FOUND)
  pkg_check_modules(GIO QUIET IMPORTED_TARGET gio-2.0 gio-unix-2.0)
  if(GIO_FOUND)
    add_library(lrdp_portal_session src/portal_session.cpp)
    target_link_libraries(lrdp_portal_session PUBLIC lrdp_protocol PkgConfig::GIO)
    target_compile_options(lrdp_portal_session PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
  endif()
endif()
