add_library(lrdp_clipboard_files src/clipboard_file_store.cpp)
target_link_libraries(lrdp_clipboard_files PUBLIC lrdp_protocol)
target_compile_options(lrdp_clipboard_files PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
target_link_libraries(lrdpd PRIVATE lrdp_clipboard_files)
if(BUILD_TESTING)
  add_executable(lrdp_file_store_tests tests/file_store_tests.cpp)
  target_link_libraries(lrdp_file_store_tests PRIVATE lrdp_clipboard_files)
  add_test(NAME clipboard_file_store COMMAND lrdp_file_store_tests)
endif()
