target_sources(lrdp_protocol PRIVATE src/extended_wire.cpp src/extended_input.cpp src/touch_injector.cpp src/session_extended_input.cpp)
if(BUILD_TESTING)
  add_executable(lrdp_extended_input_tests tests/extended_input_tests.cpp)
  target_link_libraries(lrdp_extended_input_tests PRIVATE lrdp_protocol)
  add_test(NAME extended_input COMMAND lrdp_extended_input_tests)
  add_executable(lrdp_touch_injector_tests tests/touch_injector_tests.cpp)
  target_link_libraries(lrdp_touch_injector_tests PRIVATE lrdp_protocol)
  add_test(NAME touch_injector COMMAND lrdp_touch_injector_tests)
  add_executable(lrdp_extended_session_tests tests/extended_session_tests.cpp)
  target_link_libraries(lrdp_extended_session_tests PRIVATE lrdp_protocol)
  add_test(NAME extended_session COMMAND lrdp_extended_session_tests)
endif()
